apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-emb-4b
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: storage-nvme-c2
  volumeMode: Filesystem
