apiVersion: v1
kind: Service
metadata:
  name: qwen3-emb-4b
  namespace: default
spec:
  ports:
  - name: http-vllm
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: qwen3-emb-4b
  sessionAffinity: None
  type: LoadBalancer
